### PR TITLE
enable-ec_nistp_64_gcc_128 configuration

### PR DESCRIPTION
**Pull request by gpongelli**
Set enable-ec_nistp_64_gcc_128 configuration for x64 archs

### CODE REVIEW

**Comment by x2on** [comment]
Hi,

What does this flag do?

**Comment by gpongelli** [comment]
[OpenSSL Compilation wiki](https://wiki.openssl.org/index.php/Compilation_and_Installation#Configure_Options) tells `Use on x64 platforms when GCC supports __uint128_t. ECDH is about 2 to 4 times faster.` so it's used to speed up Elliptic Curve Diffie-Hellman for x64 architecture.
I've added it as an option because not everyone uses Elliptic Curve, while I do.

**Comment by x2on** [comment]
Ok Sounds good - is it supported on arm64 ?

**Comment by gpongelli** [comment]
Do you mean if it compiles on arm64? Yes

**Comment by x2on** [comment]
Thanks for your PR

**Pull request merged**
