### PR TITLE
Change MIN_SDK_VERSION to 7.0

### LINKED ISSUE #56: Support for bitcode?
I'm finding that when I build this project and include in am Xcode 7 / iOS 9 project, I can't enable bitcode because OpenSSL was not compiled with bitcode enabled. I've been able to build the project with Xcode 7 beta, but I think OpenSSL itself is being built with GCC?

Thanks for this project!

### PR DESCRIPTION
**Pull request by x2on**
Fixes #56

### CODE REVIEW

**Comment by benf1977** [comment]
It looks like it should work, but after building the i386 simulator lib, the script prints out this:

    making all in tools...
    make[1]: Nothing to be done for `all'.

Then quietly exits.

**Comment by x2on** [comment]
@benf1977 : here it runs fine... could you please have a look at the `bin` folder or run with `verbose` flag: `./build-libssl.h verbose`

**Comment by benf1977** [comment]
Here you go, thanks:
https://gist.github.com/benf1977/3aab0d7b508a458fad8e

(It didn't actually take an hour to build, I just didn't get back to the terminal window for a while).

**Comment by benf1977** [comment]
After the latest pull, everything builds perfectly. Thanks much!

**Pull request merged**
