### PR TITLE
Added configuration option variable.

### PR DESCRIPTION
**Pull request by gpongelli**
Added "make depend", to be run when disabling algorithms and "install_sw" to install only software without docs.

### CODE REVIEW

**Comment by x2on** [comment]
Why is make depend needed?

**Comment by gpongelli** [comment]
Because if you disable one or more algorithms you've to run make depend.
For example, if you run manually on a fresh extracted 1.0.2c version something like this
`./Configure darwin64-x86_64-cc no-ssl2` 
at the end it will appear this message
```
Since you've disabled or enabled at least one algorithm, you need to do
the following before building:

	make depend
```

I usually use a configuration option to disable algorithms, so I've added it.

**Comment by x2on** [comment]
Ok, thanks for explanation!
Would be nice if that only runs if the CONFIG_OPTIONS are not a empty string to prevent slow down of normal build, or?

**Comment by gpongelli** [comment]
I thought to add the check but I've had some problems with my long options, now solved and added.

**Comment by x2on** [comment]
Thanks a lot for this PR!

**Comment by gpongelli** [comment]
You're welcome.
I'm working on a couple of other PR I'll send you soon.

**Pull request merged**
