### PR TITLE
Build loop: minimise file edits (use Configure options instead) and minor style changes

### PR DESCRIPTION
**Pull request by oneton**
- Increase script 'safety' by checking for undefined variables
- Add comments, remove unused variables
- Align name of SOURCEDIR var with other vars
- Add compiler arguments and defines to LOCAL_CONFIG_OPTIONS where possible
- Remove change to ui_openssl.c since sig_atomic_t is now defined in the iOS SDK (also checked for 7.1) and removing it shows a compiler warning (ui_openssl.c:410:17: warning: type specifier missing, defaults to 'int' [-Wimplicit-int])
- Only add -isysroot option to Darwin builds since it is part of the compiler arguments for the iphoneos-cross target

### CODE REVIEW

**Comment by oneton** [comment]
I wonder if we should disable the parallel build by default. Travis was able to complete the same build without errors on my repository... https://travis-ci.org/oneton/OpenSSL-for-iPhone

**Comment by x2on** [comment]
Hm thats interesting... But it was also build parallel on your build, or?

**Comment by oneton** [comment]
My build was indeed also parallel. I think I saw this error once during testing and figured it was either related to a parallel build or leftover files from a previous test. The next run it went fine. A re-run might actually complete successfully.

I'm having trouble finding the iOS 7.0 SDK, I could simply find 7.1 with Google. I'll try to trigger a Travis test build on Xcode 6.3 / iOS 7.0

**Comment by x2on** [comment]
Hm ok we could run the build on travis always without parallel (command line option?) - That could avoid problems here.

We could also drop iOS 7.0 and only support > iOS 8 since iOS 10 is released.

**Comment by oneton** [comment]
It sounds like a safe approach to switch it off for Travis builds. My last effort for today (I hope I'm not keeping you too busy ;)) will be a pull request with command line options. So we can benefit from that straight away.

I found out that I didn't read the Travis docs properly, the 7.0 SDK is not available. I just downloaded Xcode 5 and checked the SDK. In arm/signal.h the typedef is present, so the change would be safe, even for iOS 7.0.

Apple says there's only 3% left using < iOS 8.0 https://developer.apple.com/support/app-store/ so I would be in favour of moving to iOS 8 (also since we can't even test using Travis).

**Pull request merged**
